version: "3"
# Rede de comunicação entre containers
networks:
  avfweb-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.1/24

services:
    
    # AVFWEB-API
    avfweb-api:
        container_name: avfweb-api
        image: php:8.0-apache
        restart: always
        build:
            context: '.'
        ports:
          - "8080:80"
        networks:
          - avfweb-network
        volumes:
          - D:/Vinicius/www/avfweb_api:/var/www/html/
        tty: true  
          
    avfweb_db:
      container_name: avfweb_db
      image: mysql
      ports:
        - "3306:3306"
      expose:
        - 3306
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=avfweb_db
        - MYSQL_USER=avfwebroot
        - MYSQL_PASSWORD=password
        - MYSQL_ALLOW_EMPTY_PASSWORD=password
        
      volumes:
        - D:/Vinicius/www/avfweb_db:/var/lib/mysql 
      networks:
        - avfweb-network   
   
   