version: "3.8"
# Rede de comunicação entre containers
networks:
  avfweb-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.1/24

services:
    
    # BASE DE DADOS  
    avfweb_db:
        container_name: avfweb_dbo
        image: mysql:latest
        ports:
            - "3307:3306"
        expose: 
            - "3307"  
        env_file:
            - ./.env            
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD} 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}            
        volumes:
            - D:/Vinicius/www/avfweb_db:${DB_WORK_DIR}          
        networks:
            - avfweb-network     
           
        
    
    # AVFWEB-API
    avfweb-api:
        container_name: avfweb-api
        build:
            dockerfile: Dockerfile
            
        image: php:8.0-apache
        restart: always
        ports:
          - "8080:80"
        env_file:
            - ./.env   
        networks:
          - avfweb-network
        volumes:
          - D:/Vinicius/www/avfweb_api:${WORK_DIR}
        working_dir: ${WORK_DIR}
        depends_on:
            - avfweb_db
        links:
            - avfweb_db  
        tty: true  
          
    # Sistema
    avfweb-back:
        container_name: avfweb-sistema
        build:
            dockerfile: Dockerfile
                    
        image: php:8.0-apache
        restart: always
        
        ports:
          - "8081:80"
        env_file:
            - ./.env   
        networks:
          - avfweb-network
        volumes:
          - D:/Vinicius/www/avfweb_sistema:${WORK_DIR}/public
        working_dir: ${WORK_DIR}          
        depends_on:
            - avfweb_db
        links:
            - avfweb_db            
        tty: true          

    # Sistema
    avfweb-front:
        container_name: avfweb-front
        build:
            dockerfile: Dockerfile
            
        image: php:8.0-apache
        restart: always
        ports:
          - "8082:80"
        env_file:
            - ./.env   
        networks:
          - avfweb-network
        volumes:
          - D:/Vinicius/www/avfweb_front:${WORK_DIR}/public
        working_dir: ${WORK_DIR}          
        depends_on:
            - avfweb_db
        links:
            - avfweb_db            
        tty: true  

 

volumes: 
    avfweb_db:
